export { default as FcSection } from './section/FcSection.vue'
export { default as FcSectionHeader } from './section/FcSectionHeader.vue'
export { default as FcSectionCard } from './display/FcSectionCard.vue'
export { default as FcEmpty } from './display/FcEmpty.vue'
export { default as FcSkeleton } from './display/FcSkeleton.vue'
export { default as FcTag } from './display/FcTag.vue'
export { default as FcTagGroup } from './display/FcTagGroup.vue'
export { default as FcAvatar } from './display/FcAvatar.vue'
export { default as FcImage } from './display/FcImage.vue'
export { default as FcStatusBadge } from './data/FcStatusBadge.vue'
export { default as FcReorderableGrid } from './data/FcReorderableGrid.vue'
export { default as FcTable } from './data/FcTable.vue'
export type { TableColumn } from './data/_types'
export { default as FcDialog } from './overlay/FcDialog.vue'
export { default as FcDrawer } from './overlay/FcDrawer.vue'
export { default as FcPopover } from './overlay/FcPopover.vue'
export { default as FcTooltip } from './overlay/FcTooltip.vue'
export { default as FcConfirm } from './overlay/FcConfirm.vue'
export { default as FcContextMenu } from './overlay/FcContextMenu.vue'
export { default as FcPicker } from './overlay/FcPicker.vue'
export { default as FcPickerGroup } from './overlay/FcPickerGroup.vue'
export { default as FcImagePicker } from './overlay/FcImagePicker.vue'
export type { FcImagePickerServerConfig, FcImagePickerProps } from './overlay/FcImagePicker.vue'
export { default as FcDropZone } from './form/FcDropZone.vue'
export { default as FcButton } from './form/FcButton.vue'
export { default as FcInput } from './form/FcInput.vue'
export { default as FcSelect } from './form/FcSelect.vue'
export type { SelectOption } from './form/_types'
export { default as FcFormItem } from './form/FcFormItem.vue'
export { default as FcSwitch } from './form/FcSwitch.vue'
export { default as FcFilterBar } from './navigation/FcFilterBar.vue'
export { default as FcFilterBarDivider } from './navigation/FcFilterBarDivider.vue'
export { default as FcFilterButton } from './navigation/FcFilterButton.vue'
export { default as FcSegmented } from './navigation/FcSegmented.vue'
export { default as FcTabsPanel } from './navigation/FcTabsPanel.vue'
export { default as FcPagination } from './navigation/FcPagination.vue'
export { default as FcHeader } from './layout/FcHeader.vue'
export { default as FcMain } from './layout/FcMain.vue'
export { default as FcSidebar } from './layout/FcSidebar.vue'
export { default as FcSidebarNav } from './layout/FcSidebarNav.vue'
export { default as FcNavGroup } from './layout/FcNavGroup.vue'
export { default as FcSidePanel } from './layout/FcSidePanel.vue'
export { default as FcSidebarToggle } from './layout/FcSidebarToggle.vue'

// ===== nav 类型 (re-export) =====
export type { NavLeaf, NavGroup, NavItem } from './layout/FcSidebarNav.vue'

// ===== layout composables =====
export { useRouteAccess, filterRoutes } from './layout/useRouteAccess'
export type { RouteAccessOptions } from './layout/useRouteAccess'
export { buildNavItems } from './layout/buildNavItems'
export type { BuildNavOptions, NavGroupRule, NavTopLevelRule } from './layout/buildNavItems'
export { useSidebarNavItems } from './layout/useSidebarNavItems'
export type { UseSidebarNavOptions } from './layout/useSidebarNavItems'

// ===== theme =====
export { default as FcThemeProvider } from './theme/FcThemeProvider.vue'
export { default as FcThemeSwitcher } from './theme/FcThemeSwitcher.vue'
export { BRANDS, THEMES, getBrand, isValidBrand } from './theme/brands'
export type { BrandMeta, ThemeMeta, ThemeMode } from './theme/brands'
